#!/bin/bash

set -o errexit

set -o nounset

worker_ready() {
    celery -A papss_config inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers not available'
    sleep 1
done
>&2 echo 'Celery workers are available and ready'

celery \
    --app=papss_config \
    --broker="${CELERY_BROKER}" \
    flower